spring:
  application:
    name: AttributeAuthority
  couchbase:
    env:
      timeouts:
        connect: 10000
        query: 75000
        view: 75000
        socket-connect: 10000
    bootstrap-hosts: localhost
    bucket:
      name: aa.tu-berlin.de
      password: foobar
server:
  port: 9002
  ssl:
    key-store: /home/anrock/Documents/Sem12_Inf/masterarbeit/tutorials/spring-security-x509/keystore/keystore.jks
    key-store-password: foobar
    key-alias: localhost
    ca-alias: ca
    key-password: foobar
    enabled: true
    client-auth: need
    trust-store: /home/anrock/Documents/Sem12_Inf/masterarbeit/tutorials/spring-security-x509/keystore/truststore.jks
    trust-store-password: foobar

attribute-authority:
  id: "aa.tu-berlin.de"
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: aa-test
      password: password

attribute-authority:
  requestGPPOnInit: false
