spring:
  application:
    name: CentralServer
  couchbase:
    env:
      timeouts:
        connect: 10000
        query: 75000
        view: 75000
        socket-connect: 10000
    bootstrap-hosts: localhost
    bucket:
      name: ca
      password: foobar

server:
  port: 9001
  ssl:
    key-store: classpath:ca-keystore.jks
    key-store-password: foobar
    key-alias: localhost
    ca-alias: ca
    key-password: foobar
    enabled: true
    client-auth: want
    trust-store: classpath:ca-truststore.jks
    trust-store-password: foobar

central-server:
  credentials:
    username: admin
    password: password
  certificate:
    domains:
      - localhost
      - server.vpn
      - undo.life
    ips:
      - 127.0.0.1
      - 10.8.0.1
      - 81.169.220.55
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: ca-test
      password: password
