spring:
  application:
    name: CentralServer
  couchbase:
    env:
      timeouts:
        connect: 10000
        query: 75000
        view: 75000
        socket-connect: 10000
    bootstrap-hosts: localhost
    bucket:
      name: ca
      password: foobar

server:
  port: 9001
  ssl:
    key-store: /home/anrock/Documents/Sem12_Inf/masterarbeit/tutorials/spring-security-x509/keystore/keystore.jks
    key-store-password: foobar
    key-alias: localhost
    ca-alias: ca
    key-password: foobar
    enabled: false # TODO: enable, but restTempalte and eurka feign client will fail
    # client-auth: need
    trust-store: /home/anrock/Documents/Sem12_Inf/masterarbeit/tutorials/spring-security-x509/keystore/truststore.jks
    trust-store-password: foobar
  security: # TODO: remove
    user:
      name: Admin
      password: admin

central-server:
  credentials:
    username: admin
    password: password
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: ca-test
      password: password

server:
  ssl:
    enabled: false
