spring:
  application:
    name: CentralServer
  couchbase:
    env:
      timeouts:
        connect: 10000
        query: 75000
        view: 75000
        socket-connect: 10000
    bootstrap-hosts: localhost
    bucket:
      name: ca
      password: foobar

server:
  port: 9001
  ssl:
    key-store: classpath:ca-keystore.jks
    key-store-password: foobar
    key-alias: localhost
    ca-alias: ca
    key-password: foobar
    enabled: false # TODO: enable, but restTempalte and eurka feign client will fail
    client-auth: want
    trust-store: classpath:ca-truststore.jks
    trust-store-password: foobar
  security: # TODO: remove
    user:
      name: Admin
      password: admin

central-server:
  credentials:
    username: admin
    password: password
  certificate:
    domain: localhost
    ip: 127.0.0.1
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: ca-test
      password: password

server:
  ssl:
    enabled: false
