spring:
  application:
    name: AttributeAuthority
  couchbase:
    env:
      timeouts:
        connect: 10000
        query: 75000
        view: 75000
        socket-connect: 10000
    bootstrap-hosts: localhost
    bucket:
      name: aa.tu-berlin.de
      password: foobar
server:
  port: 9002
  ssl:
    key-store: classpath:aa-authority-keystore.jks
    key-store-password: foobar
    key-alias: localhost
    ca-alias: ca
    key-password: foobar
    enabled: false
    # client-auth: need
    trust-store: classpath:aa-truststore.jks
    trust-store-password: foobar

attribute-authority:
  id: "aa.tu-berlin.de"
  caRootUrl: "https://localhost:9001/"
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: aa-test
      password: password

attribute-authority:
  request-ca-on-init: false
