spring:
  application:
    name: Client

client:
  db:
    data-dir: data-client
  ca-root-url: https://server.vpn:9001/
  # the url of this devices attribute authority
  aa-root-url: https://server.vpn:9002/
  csp-root-url: https://server.vpn:9003/
  private-key:
    location: ./
    key-alias: key
    key-store-password: foobar
    key-password: foobar
  p12-certificate:
    location: ./p12/
    key-store-password: foobar
    key-password: foobar
  trust-store: classpath:ca-truststore.jks
  trust-store-password: foobar
---
spring:
  profiles: test

client:
  ca-root-url: https://localhost:9001/
  aa-root-url: https://localhost:9002/
  csp-root-url: https://localhost:9003/
