spring:
  application:
    name: Client

client:
  db:
    data-dir: data-client
  ca-root-url: https://server.vpn:9001/
  private-key:
    location: ./
    key-alias: key
    key-store-password: foobar
    key-password: foobar
  p12-certificate:
    location: ./p12/
    key-store-password: foobar
    key-password: foobar
  trust-store: classpath:ca-truststore.jks
  trust-store-password: foobar
